"""initial schema

Revision ID: dd871dd24d18
Revises: 
Create Date: 2025-11-07 16:13:55.549649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd871dd24d18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('markup_schemas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('PM', 'SOURCING', 'LEADERSHIP', 'ADMIN', name='role_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=32), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=True),
    sa.Column('service_type', sa.Enum('design', 'pcba', 'im', 'prototyping', name='service_enum'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('intake', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calc_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_files_project_id'), 'files', ['project_id'], unique=False)
    op.create_table('internal_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_estimates_project_id'), 'internal_estimates', ['project_id'], unique=False)
    op.create_table('rfqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rfqs_project_id'), 'rfqs', ['project_id'], unique=False)
    op.create_index(op.f('ix_rfqs_status'), 'rfqs', ['status'], unique=False)
    op.create_table('supplier_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('supplier_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('tooling_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('moq', sa.Integer(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_quotes_rfq_id'), 'supplier_quotes', ['rfq_id'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_status'), 'supplier_quotes', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_quotes_supplier_name'), 'supplier_quotes', ['supplier_name'], unique=False)
    op.create_table('customer_quotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('selected_supplier_quote_id', sa.Integer(), nullable=True),
    sa.Column('markup_schema_id', sa.Integer(), nullable=False),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fees', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['markup_schema_id'], ['markup_schemas.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['selected_supplier_quote_id'], ['supplier_quotes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_quotes_project_id'), 'customer_quotes', ['project_id'], unique=False)
    op.create_index(op.f('ix_customer_quotes_status'), 'customer_quotes', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_quotes_status'), table_name='customer_quotes')
    op.drop_index(op.f('ix_customer_quotes_project_id'), table_name='customer_quotes')
    op.drop_table('customer_quotes')
    op.drop_index(op.f('ix_supplier_quotes_supplier_name'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_status'), table_name='supplier_quotes')
    op.drop_index(op.f('ix_supplier_quotes_rfq_id'), table_name='supplier_quotes')
    op.drop_table('supplier_quotes')
    op.drop_index(op.f('ix_rfqs_status'), table_name='rfqs')
    op.drop_index(op.f('ix_rfqs_project_id'), table_name='rfqs')
    op.drop_table('rfqs')
    op.drop_index(op.f('ix_internal_estimates_project_id'), table_name='internal_estimates')
    op.drop_table('internal_estimates')
    op.drop_index(op.f('ix_files_project_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('markup_schemas')
    # ### end Alembic commands ###
